[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["npm ci --production"]

[phases.build]
cmds = ["echo 'Build completed - no compilation needed for Node.js'"]

[start]
cmd = "node server.js"